# Generated by Django 5.1.3 on 2025-03-19 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
