# Generated by Django 5.1.3 on 2025-03-19 17:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
