# Generated by Django 5.1.3 on 2025-03-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_customers_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидание'), ('attended', 'Пришел')], default='pending', max_length=10),
        ),
    ]
